name: Deploy Angular Website

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  # Lets workflow to be run from the Actions tab
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: "12"
      - name: Install Dependencies
        run: |
          npm install
          npm install -g @angular/cli > /dev/null
      - name: Build Website
        run: |
          ng build --prod --base-href 'https://mochitarts.github.io/'
          cp ./dist/index.html ./dist/404.html
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}