name: Build and Deploy

on:
  push:
    branches:
      - develop
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '12'

    - name: Build
      run: |
        npm install
        npm install -g @angular/cli@9.1.15 > /dev/null
        ng build --prod --base-href 'https://mochitarts.github.io/'
        cp ./dist/index.html ./dist/404.html
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: dist